/*
 * Copyright (c) 2008 Kasper Nielsen.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * This class was automatically generated by cake.bootstrap.codegen.model.GenerateModel
 * Available in the https://github.com/cakeframework/cake-developers/ project
 */
package io.faststream.codegen.model.visitor;

import io.faststream.codegen.model.AbstractASTNode;
import io.faststream.codegen.model.PackageDeclaration;
import io.faststream.codegen.model.body.FieldDeclaration;
import io.faststream.codegen.model.body.InitializerDeclaration;
import io.faststream.codegen.model.body.Parameter;
import io.faststream.codegen.model.body.VariableDeclarator;
import io.faststream.codegen.model.expression.ArrayAccessExpression;
import io.faststream.codegen.model.expression.ArrayCreationExpression;
import io.faststream.codegen.model.expression.AssignExpression;
import io.faststream.codegen.model.expression.BinaryExpression;
import io.faststream.codegen.model.expression.CastExpression;
import io.faststream.codegen.model.expression.ClassExpression;
import io.faststream.codegen.model.expression.ConditionalExpression;
import io.faststream.codegen.model.expression.EncapsulatedExpression;
import io.faststream.codegen.model.expression.Expression;
import io.faststream.codegen.model.expression.FieldAccessExpression;
import io.faststream.codegen.model.expression.InstanceOfExpression;
import io.faststream.codegen.model.expression.Literal;
import io.faststream.codegen.model.expression.MethodInvocation;
import io.faststream.codegen.model.expression.NameExpression;
import io.faststream.codegen.model.expression.NewInstanceExpression;
import io.faststream.codegen.model.expression.SuperExpression;
import io.faststream.codegen.model.expression.ThisExpression;
import io.faststream.codegen.model.expression.UnaryExpression;
import io.faststream.codegen.model.expression.VariableDeclarationExpression;
import io.faststream.codegen.model.statement.AssertStatement;
import io.faststream.codegen.model.statement.BlockStatement;
import io.faststream.codegen.model.statement.BreakStatement;
import io.faststream.codegen.model.statement.CatchClause;
import io.faststream.codegen.model.statement.ContinueStatement;
import io.faststream.codegen.model.statement.DoStatement;
import io.faststream.codegen.model.statement.EmptyStatement;
import io.faststream.codegen.model.statement.ExplicitConstructorInvocationStatement;
import io.faststream.codegen.model.statement.ExpressionStatement;
import io.faststream.codegen.model.statement.ForStatement;
import io.faststream.codegen.model.statement.IfStatement;
import io.faststream.codegen.model.statement.LabeledStatement;
import io.faststream.codegen.model.statement.ReturnStatement;
import io.faststream.codegen.model.statement.Statement;
import io.faststream.codegen.model.statement.SwitchEntryStatement;
import io.faststream.codegen.model.statement.SwitchStatement;
import io.faststream.codegen.model.statement.SynchronizedStatement;
import io.faststream.codegen.model.statement.TextLineStatement;
import io.faststream.codegen.model.statement.ThrowStatement;
import io.faststream.codegen.model.statement.TryStatement;
import io.faststream.codegen.model.statement.WhileStatement;
import io.faststream.codegen.model.type.ClassOrInterfaceType;
import io.faststream.codegen.model.type.PrimitiveType;
import io.faststream.codegen.model.type.ReferenceType;

/**
 * This class has been autogenerated
 *
 * @author Kasper Nielsen
 */
public abstract class CodegenVisitor {

    public void visit(PackageDeclaration n) {
        visitNodeBefore(n);
        n.getName().accept(this);
        visitNodeAfter(n);
    }

    public void visit(Parameter n) {
        visitNodeBefore(n);
        visitNodeAfter(n);
    }

    public void visit(InitializerDeclaration n) {
        visitNodeBefore(n);
        n.getBody().accept(this);
        visitNodeAfter(n);
    }

    public void visit(FieldDeclaration n) {
        visitNodeBefore(n);
        n.getType().accept(this);
        n.getDeclarators().accept(this);
        visitNodeAfter(n);
    }

    public void visit(VariableDeclarator n) {
        visitNodeBefore(n);
        n.getName().accept(this);
        n.getInit().accept(this);
        visitNodeAfter(n);
    }

    public void visit(ArrayCreationExpression n) {
        visitNodeBefore(n);
        n.getType().accept(this);
        for (Expression nn : n) {
            nn.accept(this);
        }
        visitNodeAfter(n);
    }

    public void visit(ArrayAccessExpression n) {
        visitNodeBefore(n);
        n.getArray().accept(this);
        for (Expression nn : n) {
            nn.accept(this);
        }
        visitNodeAfter(n);
    }

    public void visit(AssignExpression n) {
        visitNodeBefore(n);
        n.getLeft().accept(this);
        n.getRight().accept(this);
        visitNodeAfter(n);
    }

    public void visit(BinaryExpression n) {
        visitNodeBefore(n);
        n.getLeft().accept(this);
        n.getRight().accept(this);
        visitNodeAfter(n);
    }

    public void visit(CastExpression n) {
        visitNodeBefore(n);
        n.getType().accept(this);
        n.getExpression().accept(this);
        visitNodeAfter(n);
    }

    public void visit(ClassExpression n) {
        visitNodeBefore(n);
        n.getType().accept(this);
        visitNodeAfter(n);
    }

    public void visit(ConditionalExpression n) {
        visitNodeBefore(n);
        n.getCondition().accept(this);
        n.getThenExpression().accept(this);
        n.getElseExpression().accept(this);
        visitNodeAfter(n);
    }

    public void visit(EncapsulatedExpression n) {
        visitNodeBefore(n);
        n.getInner().accept(this);
        visitNodeAfter(n);
    }

    public void visit(FieldAccessExpression n) {
        visitNodeBefore(n);
        if (n.getScope() != null) {
            n.getScope().accept(this);
        }
        visitNodeAfter(n);
    }

    public void visit(InstanceOfExpression n) {
        visitNodeBefore(n);
        n.getExpression().accept(this);
        n.getType().accept(this);
        visitNodeAfter(n);
    }

    public void visit(MethodInvocation n) {
        visitNodeBefore(n);
        n.getScope().accept(this);
        for (Expression nn : n) {
            nn.accept(this);
        }
        visitNodeAfter(n);
    }

    public void visit(NameExpression n) {
        visitNodeBefore(n);
        visitNodeAfter(n);
    }

    public void visit(NewInstanceExpression n) {
        visitNodeBefore(n);
        if (n.getScope() != null) {
            n.getScope().accept(this);
        }
        n.getType().accept(this);
        for (Expression nn : n) {
            nn.accept(this);
        }
        visitNodeAfter(n);
    }

    public void visit(ThisExpression n) {
        visitNodeBefore(n);
        n.getClassExpression().accept(this);
        visitNodeAfter(n);
    }

    public void visit(SuperExpression n) {
        visitNodeBefore(n);
        n.getClassExpression().accept(this);
        visitNodeAfter(n);
    }

    public void visit(UnaryExpression n) {
        visitNodeBefore(n);
        n.getExpression().accept(this);
        visitNodeAfter(n);
    }

    public void visit(VariableDeclarationExpression n) {
        visitNodeBefore(n);
        n.getType().accept(this);
        for (VariableDeclarator nn : n) {
            nn.accept(this);
        }
        visitNodeAfter(n);
    }

    public void visit(Literal n) {
        visitNodeBefore(n);
        visitNodeAfter(n);
    }

    public void visit(AssertStatement n) {
        visitNodeBefore(n);
        n.getCheck().accept(this);
        n.getMessage().accept(this);
        visitNodeAfter(n);
    }

    public void visit(BlockStatement n) {
        visitNodeBefore(n);
        for (Statement nn : n) {
            nn.accept(this);
        }
        visitNodeAfter(n);
    }

    public void visit(BreakStatement n) {
        visitNodeBefore(n);
        visitNodeAfter(n);
    }

    public void visit(CatchClause n) {
        visitNodeBefore(n);
        n.getParameter().accept(this);
        n.getBody().accept(this);
        visitNodeAfter(n);
    }

    public void visit(ContinueStatement n) {
        visitNodeBefore(n);
        visitNodeAfter(n);
    }

    public void visit(TextLineStatement n) {
        visitNodeBefore(n);
        visitNodeAfter(n);
    }

    public void visit(ExpressionStatement n) {
        visitNodeBefore(n);
        n.getExpression().accept(this);
        visitNodeAfter(n);
    }

    public void visit(ForStatement n) {
        visitNodeBefore(n);
        for (Expression nn : n.getInit()) {
            nn.accept(this);
        }
        if (n.getCompare() != null) {
            n.getCompare().accept(this);
        }
        for (Expression nn : n.getUpdate()) {
            nn.accept(this);
        }
        n.getBody().accept(this);
        visitNodeAfter(n);
    }

    public void visit(DoStatement n) {
        visitNodeBefore(n);
        n.getCondition().accept(this);
        n.getBody().accept(this);
        visitNodeAfter(n);
    }

    public void visit(ExplicitConstructorInvocationStatement n) {
        visitNodeBefore(n);
        for (Expression nn : n) {
            nn.accept(this);
        }
        visitNodeAfter(n);
    }

    public void visit(EmptyStatement n) {
        visitNodeBefore(n);
        visitNodeAfter(n);
    }

    public void visit(IfStatement n) {
        visitNodeBefore(n);
        n.getCondition().accept(this);
        n.getThenStatement().accept(this);
        if (n.getElseStatement() != null) {
            n.getElseStatement().accept(this);
        }
        visitNodeAfter(n);
    }

    public void visit(LabeledStatement n) {
        visitNodeBefore(n);
        n.getStatement().accept(this);
        visitNodeAfter(n);
    }

    public void visit(ReturnStatement n) {
        visitNodeBefore(n);
        if (n.getExpression() != null) {
            n.getExpression().accept(this);
        }
        visitNodeAfter(n);
    }

    public void visit(SynchronizedStatement n) {
        visitNodeBefore(n);
        n.getMutex().accept(this);
        n.getBlock().accept(this);
        visitNodeAfter(n);
    }

    public void visit(SwitchEntryStatement n) {
        visitNodeBefore(n);
        n.getLabel().accept(this);
        for (Statement nn : n.getStatements()) {
            nn.accept(this);
        }
        visitNodeAfter(n);
    }

    public void visit(SwitchStatement n) {
        visitNodeBefore(n);
        n.getSelect().accept(this);
        for (SwitchEntryStatement nn : n) {
            nn.accept(this);
        }
        visitNodeAfter(n);
    }

    public void visit(ThrowStatement n) {
        visitNodeBefore(n);
        n.getExpression().accept(this);
        visitNodeAfter(n);
    }

    public void visit(TryStatement n) {
        visitNodeBefore(n);
        n.getTryBlock().accept(this);
        for (CatchClause nn : n.getCatchClauses()) {
            nn.accept(this);
        }
        n.getFinallyBlock().accept(this);
        visitNodeAfter(n);
    }

    public void visit(WhileStatement n) {
        visitNodeBefore(n);
        n.getCondition().accept(this);
        n.getBody().accept(this);
        visitNodeAfter(n);
    }

    public void visit(ClassOrInterfaceType n) {
        visitNodeBefore(n);
        visitNodeAfter(n);
    }

    public void visit(PrimitiveType n) {
        visitNodeBefore(n);
        visitNodeAfter(n);
    }

    public void visit(ReferenceType n) {
        visitNodeBefore(n);
        visitNodeAfter(n);
    }

    public void visitNodeBefore(AbstractASTNode e) {}

    public void visitNodeAfter(AbstractASTNode e) {}
}
