/*
 * Copyright (c) 2008 Kasper Nielsen.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/* 
 * This class was automatically generated by cake.bootstrap.view.GenerateAll 
 * Available in the https://github.com/cakeframework/cake-developers/ project 
 */
package org.cakeframework.internal.db.nodes.view.mapview;

/**
 * This class has been autogenerated
 *
 * @author Kasper Nielsen
 */
import java.util.Objects;

import org.cakeframework.internal.db.query.node.QueryOperationNode;
import org.cakeframework.internal.db.query.node.QueryOperationNodeDefinition;
import org.cakeframework.internal.db.query.node.defaults.MapQueryOperations;
import org.cakeframework.util.BiComparator;

@SuppressWarnings("rawtypes")
public class MV_Sorted extends AbstractMapView implements MapViewVisitable {

    private static final long serialVersionUID = 1L;

    private final BiComparator biComparator;

    public MV_Sorted(QueryOperationNode parent, BiComparator biComparator) {
        super(parent);
        this.biComparator = Objects.requireNonNull(biComparator, "biComparator is null");
    }

    public QueryOperationNodeDefinition getOperationPackage() {
        return QueryOperationNodeDefinition.create(MapQueryOperations.M_SORTED_COMPARATOR, "biComparator", BiComparator.class);
    }

    public String name() {
        return "sorted";
    }

    public int getNodeId() {
        return 11;
    }

    @Override
    public final int getNodeType() {
        return 6;
    }

    public BiComparator getBiComparator() {
        return biComparator;
    }

    public void accept(MapViewVisitable.MapViewVisitor visitor) {
        visitor.sorted(this);
    }
}
