/*
 * Copyright (c) 2008 Kasper Nielsen.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/* 
 * This class was automatically generated by cake.bootstrap.view.GenerateAll 
 * Available in the https://github.com/cakeframework/cake-developers/ project 
 */
package org.cakeframework.internal.db.nodes.view.mapview;

/**
 * This class has been autogenerated
 *
 * @author Kasper Nielsen
 */
import org.cakeframework.internal.db.nodes.view.collectionview.AbstractCollectionView;
import org.cakeframework.internal.db.query.node.QueryOperationNode;
import org.cakeframework.internal.db.query.node.QueryOperationNodeDefinition;
import org.cakeframework.internal.db.query.node.defaults.MapQueryOperations;

public class MV_Values extends AbstractCollectionView implements MapViewVisitable {

    private static final long serialVersionUID = 1L;

    public MV_Values(QueryOperationNode parent) {
        super(parent);
    }

    public QueryOperationNodeDefinition getOperationPackage() {
        return QueryOperationNodeDefinition.create(MapQueryOperations.M_VIEW_VALUES);
    }

    public String name() {
        return "values";
    }

    public int getNodeId() {
        return 19;
    }

    @Override
    public final int getNodeType() {
        return 6;
    }

    public void accept(MapViewVisitable.MapViewVisitor visitor) {
        visitor.values(this);
    }
}
