/*
 * Copyright (c) 2008 Kasper Nielsen.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/* 
 * This class was automatically generated by cake.bootstrap.codegen.model.GenerateModel 
 * Available in the https://github.com/cakeframework/cake-developers/ project 
 */
package io.faststream.codegen.model.expression;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Objects;

import io.faststream.codegen.model.visitor.CodegenVisitor;
import io.faststream.codegen.model.visitor.ModifyingCodegenVisitor;

/**
 * This class has been autogenerated
 *
 * @author Kasper Nielsen
 */
public class ArrayAccessExpression extends Expression implements Iterable<Expression> {

    /** The array. */
    private Expression array;

    /** The indexes. */
    private List<Expression> index = new ArrayList<>(2);

    public Iterator<Expression> iterator() {
        return index.iterator();
    }

    public ArrayAccessExpression() {}

    public ArrayAccessExpression(Expression array, List<Expression> index) {
        this.array = array;
        this.index = index;
    }

    public Expression getArray() {
        return array;
    }

    public List<Expression> getIndex() {
        return index;
    }

    public void setArray(Expression array) {
        this.array = array;
    }

    public void setIndex(List<Expression> index) {
        this.index = index;
    }

    public void accept(CodegenVisitor visitor) {
        visitor.visit(this);
    }

    public Object accept(ModifyingCodegenVisitor visitor) {
        return visitor.visit(this);
    }

    /** {@inheritDoc} */
    public boolean equals(Object other) {
        return other instanceof ArrayAccessExpression && equals((ArrayAccessExpression) other);
    }

    public boolean equals(ArrayAccessExpression other) {
        return super.equals(this) && Objects.equals(array, other.array) && Objects.equals(index, other.index);
    }

    /** {@inheritDoc} */
    public int hashCode() {
        return Objects.hash(array, index);
    }
}
