/*
 * Copyright (c) 2008 Kasper Nielsen.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/* 
 * This class was automatically generated by cake.bootstrap.codegen.model.GenerateModel 
 * Available in the https://github.com/cakeframework/cake-developers/ project 
 */
package io.faststream.codegen.model.expression;

import java.util.Objects;

import io.faststream.codegen.model.visitor.CodegenVisitor;
import io.faststream.codegen.model.visitor.ModifyingCodegenVisitor;

/**
 * This class has been autogenerated
 *
 * @author Kasper Nielsen
 */
public class FieldAccessExpression extends Expression {

    /** The scope of the field access. */
    private Expression scope;

    /** The name of the field. */
    private String fieldName;

    public FieldAccessExpression() {}

    public FieldAccessExpression(Expression scope, String fieldName) {
        this.scope = scope;
        this.fieldName = fieldName;
    }

    public Expression getScope() {
        return scope;
    }

    public String getFieldName() {
        return fieldName;
    }

    public void setScope(Expression scope) {
        this.scope = scope;
    }

    public void setFieldName(String fieldName) {
        this.fieldName = fieldName;
    }

    public void accept(CodegenVisitor visitor) {
        visitor.visit(this);
    }

    public Object accept(ModifyingCodegenVisitor visitor) {
        return visitor.visit(this);
    }

    /** {@inheritDoc} */
    public boolean equals(Object other) {
        return other instanceof FieldAccessExpression && equals((FieldAccessExpression) other);
    }

    public boolean equals(FieldAccessExpression other) {
        return super.equals(this) && Objects.equals(scope, other.scope) && Objects.equals(fieldName, other.fieldName);
    }

    /** {@inheritDoc} */
    public int hashCode() {
        return Objects.hash(scope, fieldName);
    }
}
