/*
 * Copyright (c) 2008 Kasper Nielsen.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/* 
 * This class was automatically generated by cake.bootstrap.codegen.model.GenerateModel 
 * Available in the https://github.com/cakeframework/cake-developers/ project 
 */
package io.faststream.codegen.model.expression;

import java.util.Objects;

import io.faststream.codegen.model.visitor.CodegenVisitor;
import io.faststream.codegen.model.visitor.ModifyingCodegenVisitor;

/**
 * This class has been autogenerated
 *
 * @author Kasper Nielsen
 */
public class UnaryExpression extends Expression {

    /** The encasulated expression. */
    private Expression expression;

    /** The operator. */
    private UnOperator operator;

    public UnaryExpression() {}

    public UnaryExpression(Expression expression, UnOperator operator) {
        this.expression = expression;
        this.operator = operator;
    }

    public Expression getExpression() {
        return expression;
    }

    public UnOperator getOperator() {
        return operator;
    }

    public void setExpression(Expression expression) {
        this.expression = expression;
    }

    public void setOperator(UnOperator operator) {
        this.operator = operator;
    }

    public void accept(CodegenVisitor visitor) {
        visitor.visit(this);
    }

    public Object accept(ModifyingCodegenVisitor visitor) {
        return visitor.visit(this);
    }

    /** {@inheritDoc} */
    public boolean equals(Object other) {
        return other instanceof UnaryExpression && equals((UnaryExpression) other);
    }

    public boolean equals(UnaryExpression other) {
        return super.equals(this) && Objects.equals(expression, other.expression) && Objects.equals(operator, other.operator);
    }

    /** {@inheritDoc} */
    public int hashCode() {
        return Objects.hash(expression, operator);
    }

    /** The operator for the expression. */
    public enum UnOperator {
        POSITIVE("+"), 
        NEGATIVE("-"), 
        INVERSE("~"), 
        NOT("!"), 
        PRE_INCREMENT("++"), 
        PRE_DECREMENT("--"), 
        POST_INCREMENT("++"), 
        POST_DECREMENT("--");
        private final String symbol;
        private UnOperator(String symbol) {
            this.symbol = symbol;
        }

        public String toString() {
            return symbol;
        }
    }
}
