/*
 * Copyright (c) 2008 Kasper Nielsen.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/* 
 * This class was automatically generated by cake.bootstrap.view.GenerateAll 
 * Available in the https://github.com/cakeframework/cake-developers/ project 
 */
package io.faststream.query.db.nodes.view.mapview;

import io.faststream.query.db.query.node.QueryOperationNode;
import io.faststream.query.db.query.node.QueryOperationNodeDefinition;
import io.faststream.query.db.query.node.defaults.MapQueryOperations;

public class MV_Take extends AbstractMapView implements MapViewVisitable {

    private static final long serialVersionUID = 1L;

    private final long numberOfEntriesToTake;

    public MV_Take(QueryOperationNode parent, long numberOfEntriesToTake) {
        super(parent);
        if (numberOfEntriesToTake == 0) {
            throw new IllegalArgumentException("Number of entries to take cannot be 0");
        }
        this.numberOfEntriesToTake = numberOfEntriesToTake;
    }

    public QueryOperationNodeDefinition getOperationPackage() {
        return QueryOperationNodeDefinition.create(MapQueryOperations.M_TRUNCATE_TAKE, "numberOfEntriesToTake", long.class);
    }

    public String name() {
        return "take";
    }

    public int getNodeId() {
        return 18;
    }

    @Override
    public final int getNodeType() {
        return 6;
    }

    public long getNumberOfEntriesToTake() {
        return numberOfEntriesToTake;
    }

    public void accept(MapViewVisitable.MapViewVisitor visitor) {
        visitor.take(this);
    }
}
