/*
 * Copyright (c) 2008 Kasper Nielsen.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/* 
 * This class was automatically generated by cake.bootstrap.view.GenerateAll 
 * Available in the https://github.com/cakeframework/cake-developers/ project 
 */
package io.faststream.query.db.nodes.view.mapview;

/**
 * This class has been autogenerated
 *
 * @author Kasper Nielsen
 */
import java.util.Objects;
import java.util.function.BiConsumer;

import io.faststream.query.db.query.node.QueryOperationNode;
import io.faststream.query.db.query.node.QueryOperationNodeDefinition;
import io.faststream.query.db.query.node.TerminalQueryOperationNode;
import io.faststream.query.db.query.node.defaults.MapQueryOperations;

@SuppressWarnings("rawtypes")
public class MVT_ForEach extends TerminalQueryOperationNode implements MapViewVisitable {

    private static final long serialVersionUID = 1L;

    private final BiConsumer biConsumer;

    public MVT_ForEach(QueryOperationNode parent, BiConsumer biConsumer) {
        super(parent);
        this.biConsumer = Objects.requireNonNull(biConsumer, "biConsumer is null");
    }

    public QueryOperationNodeDefinition getOperationPackage() {
        return QueryOperationNodeDefinition.create(MapQueryOperations.MT_FOR_EACH_ANYORDER, "biConsumer", BiConsumer.class);
    }

    public String name() {
        return "forEach";
    }

    public int getNodeId() {
        return 86;
    }

    @Override
    public final int getNodeType() {
        return 6;
    }

    public BiConsumer getBiConsumer() {
        return biConsumer;
    }

    public void accept(MapViewVisitable.MapViewVisitor visitor) {
        visitor.forEach(this);
    }
}
