/*
 * Copyright (c) 2008 Kasper Nielsen.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/* 
 * This class was automatically generated by cake.bootstrap.view.GenerateAll 
 * Available in the https://github.com/cakeframework/cake-developers/ project 
 */
package org.cakeframework.internal.db.nodes.stream.doublestream;

/**
 * This class has been autogenerated
 *
 * @author Kasper Nielsen
 */
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.ObjDoubleConsumer;
import java.util.function.Supplier;

import org.cakeframework.internal.db.nodes.stream.StreamContext;
import org.cakeframework.internal.db.query.node.QueryOperationNode;
import org.cakeframework.internal.db.query.node.QueryOperationNodeDefinition;
import org.cakeframework.internal.db.query.node.TerminalQueryOperationNode;
import org.cakeframework.internal.db.query.node.defaults.CollectionQueryOperations;

@SuppressWarnings("rawtypes")
public class SDT_Collect extends TerminalQueryOperationNode implements DoubleStreamVisitable {

    private static final long serialVersionUID = 1L;

    private final Supplier supplier;

    private final ObjDoubleConsumer objDoubleConsumer;

    private final BiConsumer biConsumer;

    public SDT_Collect(QueryOperationNode parent, StreamContext context, Supplier supplier, ObjDoubleConsumer objDoubleConsumer, BiConsumer biConsumer) {
        super(parent);
        this.supplier = Objects.requireNonNull(supplier, "supplier is null");
        this.objDoubleConsumer = Objects.requireNonNull(objDoubleConsumer, "objDoubleConsumer is null");
        this.biConsumer = Objects.requireNonNull(biConsumer, "biConsumer is null");
        context.consume();
    }

    public QueryOperationNodeDefinition getOperationPackage() {
        return QueryOperationNodeDefinition.create(CollectionQueryOperations.CT_COLLECT_FUSED, "supplier", Supplier.class, "objDoubleConsumer", ObjDoubleConsumer.class, "biConsumer", BiConsumer.class);
    }

    public String name() {
        return "collect";
    }

    public int getNodeId() {
        return 71;
    }

    @Override
    public final int getNodeType() {
        return 5;
    }

    public Supplier getSupplier() {
        return supplier;
    }

    public ObjDoubleConsumer getObjDoubleConsumer() {
        return objDoubleConsumer;
    }

    public BiConsumer getBiConsumer() {
        return biConsumer;
    }

    public void accept(DoubleStreamVisitable.DoubleStreamVisitor visitor) {
        visitor.collect(this);
    }
}
