/*
 * Copyright (c) 2008 Kasper Nielsen.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/* 
 * This class was automatically generated by cake.bootstrap.view.GenerateAll 
 * Available in the https://github.com/cakeframework/cake-developers/ project 
 */
package io.faststream.query.db.nodes.stream.intstream;

import io.faststream.query.db.nodes.stream.StreamContext;
import io.faststream.query.db.query.node.QueryOperationNode;
import io.faststream.query.db.query.node.QueryOperationNodeDefinition;
import io.faststream.query.db.query.node.defaults.CollectionQueryOperations;

public class SI_Limit extends AbstractIntStream implements IntStreamVisitable {

    private static final long serialVersionUID = 1L;

    private final long maxSize;

    public SI_Limit(QueryOperationNode parent, StreamContext context, long maxSize) {
        super(parent, context);
        if (maxSize < 0) {
            throw new IllegalArgumentException("limit cannot be negative, was " + maxSize);
        }
        this.maxSize = maxSize;
        context.checkNotConsumed();
    }

    public QueryOperationNodeDefinition getOperationPackage() {
        return QueryOperationNodeDefinition.create(CollectionQueryOperations.C_TRUNCATE_LIMIT, "maxSize", long.class);
    }

    public String name() {
        return "limit";
    }

    public int getNodeId() {
        return 6;
    }

    @Override
    public final int getNodeType() {
        return 3;
    }

    public long getMaxSize() {
        return maxSize;
    }

    public void accept(IntStreamVisitable.IntStreamVisitor visitor) {
        visitor.limit(this);
    }
}
