/*
 * Copyright (c) 2008 Kasper Nielsen.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/* 
 * This class was automatically generated by cake.bootstrap.view.GenerateAll 
 * Available in the https://github.com/cakeframework/cake-developers/ project 
 */
package io.faststream.query.db.nodes.stream.longstream;

/**
 * This class has been autogenerated
 *
 * @author Kasper Nielsen
 */
import java.util.Objects;
import java.util.function.LongUnaryOperator;

import io.faststream.query.db.nodes.stream.StreamContext;
import io.faststream.query.db.query.node.QueryOperationNode;
import io.faststream.query.db.query.node.QueryOperationNodeDefinition;
import io.faststream.query.db.query.node.defaults.CollectionQueryOperations;

public class SL_Map extends AbstractLongStream implements LongStreamVisitable {

    private static final long serialVersionUID = 1L;

    private final LongUnaryOperator longUnaryOperator;

    public SL_Map(QueryOperationNode parent, StreamContext context, LongUnaryOperator longUnaryOperator) {
        super(parent, context);
        this.longUnaryOperator = Objects.requireNonNull(longUnaryOperator, "longUnaryOperator is null");
        context.checkNotConsumed();
    }

    public QueryOperationNodeDefinition getOperationPackage() {
        return QueryOperationNodeDefinition.create(CollectionQueryOperations.C_MAP_TO_LONG, "longUnaryOperator", LongUnaryOperator.class);
    }

    public String name() {
        return "map";
    }

    public int getNodeId() {
        return 6;
    }

    @Override
    public final int getNodeType() {
        return 4;
    }

    public LongUnaryOperator getLongUnaryOperator() {
        return longUnaryOperator;
    }

    public void accept(LongStreamVisitable.LongStreamVisitor visitor) {
        visitor.map(this);
    }
}
