/*
 * Copyright (c) 2008 Kasper Nielsen.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/* 
 * This class was automatically generated by cake.bootstrap.codegen.model.GenerateModel 
 * Available in the https://github.com/cakeframework/cake-developers/ project 
 */
package io.faststream.codegen.model.statement;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import io.faststream.codegen.model.expression.Expression;
import io.faststream.codegen.model.visitor.CodegenVisitor;
import io.faststream.codegen.model.visitor.ModifyingCodegenVisitor;

/**
 * This class has been autogenerated
 *
 * @author Kasper Nielsen
 */
public class ForStatement extends Statement {

    /** The init. */
    private List<Expression> init = new ArrayList<>(2);

    /** The compare. */
    private Expression compare;

    /** The update. */
    private List<Expression> update = new ArrayList<>(2);

    /** The body. */
    private Statement body;

    public ForStatement() {}

    public ForStatement(List<Expression> init, Expression compare, List<Expression> update, Statement body) {
        this.init = init;
        this.compare = compare;
        this.update = update;
        this.body = body;
    }

    public List<Expression> getInit() {
        return init;
    }

    public Expression getCompare() {
        return compare;
    }

    public List<Expression> getUpdate() {
        return update;
    }

    public Statement getBody() {
        return body;
    }

    public void setInit(List<Expression> init) {
        this.init = init;
    }

    public void setCompare(Expression compare) {
        this.compare = compare;
    }

    public void setUpdate(List<Expression> update) {
        this.update = update;
    }

    public void setBody(Statement body) {
        this.body = body;
    }

    public void accept(CodegenVisitor visitor) {
        visitor.visit(this);
    }

    public Object accept(ModifyingCodegenVisitor visitor) {
        return visitor.visit(this);
    }

    /** {@inheritDoc} */
    public boolean equals(Object other) {
        return other instanceof ForStatement && equals((ForStatement) other);
    }

    public boolean equals(ForStatement other) {
        return super.equals(this) && Objects.equals(init, other.init) && Objects.equals(compare, other.compare) && Objects.equals(update, other.update) && Objects.equals(body, other.body);
    }

    /** {@inheritDoc} */
    public int hashCode() {
        return Objects.hash(init, compare, update, body);
    }
}
