/*
 * Copyright (c) 2008 Kasper Nielsen.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/* 
 * This class was automatically generated by cake.bootstrap.view.GenerateAll 
 * Available in the https://github.com/cakeframework/cake-developers/ project 
 */
package io.faststream.query.db.nodes.stream.stream;

import io.faststream.query.db.nodes.stream.StreamContext;
import io.faststream.query.db.query.node.QueryOperationNode;
import io.faststream.query.db.query.node.QueryOperationNodeDefinition;
import io.faststream.query.db.query.node.defaults.CollectionQueryOperations;

public class SO_Skip extends AbstractStream implements StreamVisitable {

    private static final long serialVersionUID = 1L;

    private final long n;

    public SO_Skip(QueryOperationNode parent, StreamContext context, long n) {
        super(parent, context);
        if (n < 0) {
            throw new IllegalArgumentException("skip cannot be negative, was " + n);
        }
        this.n = n;
        context.checkNotConsumed();
    }

    public QueryOperationNodeDefinition getOperationPackage() {
        return QueryOperationNodeDefinition.create(CollectionQueryOperations.C_TRUNCATE_SKIP, "n", long.class);
    }

    public String name() {
        return "skip";
    }

    public int getNodeId() {
        return 15;
    }

    @Override
    public final int getNodeType() {
        return 2;
    }

    public long getN() {
        return n;
    }

    public void accept(StreamVisitable.StreamVisitor visitor) {
        visitor.skip(this);
    }
}
