/*
 * Copyright (c) 2008 Kasper Nielsen.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/* 
 * This class was automatically generated by cake.bootstrap.view.GenerateAll 
 * Available in the https://github.com/cakeframework/cake-developers/ project 
 */
package io.faststream.query.db.nodes.stream.stream;

import io.faststream.query.db.nodes.stream.StreamContext;
import io.faststream.query.db.query.node.QueryOperationNode;
import io.faststream.query.db.query.node.QueryOperationNodeDefinition;
import io.faststream.query.db.query.node.TerminalQueryOperationNode;
import io.faststream.query.db.query.node.defaults.CollectionQueryOperations;

public class SOT_Iterator extends TerminalQueryOperationNode implements StreamVisitable {

    private static final long serialVersionUID = 1L;

    public SOT_Iterator(QueryOperationNode parent, StreamContext context) {
        super(parent);
        context.consume();
    }

    public QueryOperationNodeDefinition getOperationPackage() {
        return QueryOperationNodeDefinition.create(CollectionQueryOperations.CT_TO_ITERATOR);
    }

    public String name() {
        return "iterator";
    }

    public int getNodeId() {
        return 20;
    }

    @Override
    public final int getNodeType() {
        return 2;
    }

    public void accept(StreamVisitable.StreamVisitor visitor) {
        visitor.iterator(this);
    }
}
