/*
 * Copyright (c) 2008 Kasper Nielsen.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/* 
 * This class was automatically generated by cake.bootstrap.view.GenerateAll 
 * Available in the https://github.com/cakeframework/cake-developers/ project 
 */
package io.faststream.query.db.nodes.stream.stream;

/**
 * This class has been autogenerated
 *
 * @author Kasper Nielsen
 */
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Supplier;

import io.faststream.query.db.nodes.stream.StreamContext;
import io.faststream.query.db.query.node.QueryOperationNode;
import io.faststream.query.db.query.node.QueryOperationNodeDefinition;
import io.faststream.query.db.query.node.TerminalQueryOperationNode;
import io.faststream.query.db.query.node.defaults.CollectionQueryOperations;

@SuppressWarnings("rawtypes")
public class SOT_CollectSupplier extends TerminalQueryOperationNode implements StreamVisitable {

    private static final long serialVersionUID = 1L;

    private final Supplier supplier;

    private final BiConsumer accumulator;

    private final BiConsumer combiner;

    public SOT_CollectSupplier(QueryOperationNode parent, StreamContext context, Supplier supplier, BiConsumer accumulator, BiConsumer combiner) {
        super(parent);
        this.supplier = Objects.requireNonNull(supplier, "supplier is null");
        this.accumulator = Objects.requireNonNull(accumulator, "accumulator is null");
        this.combiner = Objects.requireNonNull(combiner, "combiner is null");
        context.consume();
    }

    public QueryOperationNodeDefinition getOperationPackage() {
        return QueryOperationNodeDefinition.create(CollectionQueryOperations.CT_COLLECT_FUSED, "supplier", Supplier.class, "accumulator", BiConsumer.class, "combiner", BiConsumer.class);
    }

    public String name() {
        return "collectSupplier";
    }

    public int getNodeId() {
        return 14;
    }

    @Override
    public final int getNodeType() {
        return 2;
    }

    public Supplier getSupplier() {
        return supplier;
    }

    public BiConsumer getAccumulator() {
        return accumulator;
    }

    public BiConsumer getCombiner() {
        return combiner;
    }

    public void accept(StreamVisitable.StreamVisitor visitor) {
        visitor.collectSupplier(this);
    }
}
