/*
 * Copyright (c) 2008 Kasper Nielsen.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/* 
 * This class was automatically generated by cake.bootstrap.view.GenerateAll 
 * Available in the https://github.com/cakeframework/cake-developers/ project 
 */
package io.faststream.query.db.nodes.view.multimapview;

/**
 * This class has been autogenerated
 *
 * @author Kasper Nielsen
 */
import java.util.Objects;
import java.util.function.Predicate;

import io.faststream.query.db.query.node.QueryOperationNode;
import io.faststream.query.db.query.node.QueryOperationNodeDefinition;
import io.faststream.query.db.query.node.defaults.MultimapOperations;

@SuppressWarnings("rawtypes")
public class UV_FilterOnKey extends AbstractMultimapView implements MultimapViewVisitable {

    private static final long serialVersionUID = 1L;

    private final Predicate predicate;

    public UV_FilterOnKey(QueryOperationNode parent, Predicate predicate) {
        super(parent);
        this.predicate = Objects.requireNonNull(predicate, "predicate is null");
    }

    public QueryOperationNodeDefinition getOperationPackage() {
        return QueryOperationNodeDefinition.create(MultimapOperations.U_FILTER_BY_KEY_PREDICATE, "predicate", Predicate.class);
    }

    public String name() {
        return "filterOnKey";
    }

    public int getNodeId() {
        return 4;
    }

    @Override
    public final int getNodeType() {
        return 7;
    }

    public Predicate getPredicate() {
        return predicate;
    }

    public void accept(MultimapViewVisitable.MultimapViewVisitor visitor) {
        visitor.filterOnKey(this);
    }
}
