/*
 * Copyright (c) 2008 Kasper Nielsen.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/* 
 * This class was automatically generated by cake.bootstrap.view.GenerateAll 
 * Available in the https://github.com/cakeframework/cake-developers/ project 
 */
package io.faststream.query.db.nodes.view.multimapview;

import io.faststream.query.db.query.node.QueryOperationNode;
import io.faststream.query.db.query.node.QueryOperationNodeDefinition;
import io.faststream.query.db.query.node.defaults.MultimapOperations;

public class UV_TakeValues extends AbstractMultimapView implements MultimapViewVisitable {

    private static final long serialVersionUID = 1L;

    private final long numberOfValuesToTake;

    public UV_TakeValues(QueryOperationNode parent, long numberOfValuesToTake) {
        super(parent);
        if (numberOfValuesToTake == 0) {
            throw new IllegalArgumentException("Number of values to take cannot be 0");
        }
        this.numberOfValuesToTake = numberOfValuesToTake;
    }

    public QueryOperationNodeDefinition getOperationPackage() {
        return QueryOperationNodeDefinition.create(MultimapOperations.U_TRUNCATE_TAKE_VALUES, "numberOfValuesToTake", long.class);
    }

    public String name() {
        return "takeValues";
    }

    public int getNodeId() {
        return 23;
    }

    @Override
    public final int getNodeType() {
        return 7;
    }

    public long getNumberOfValuesToTake() {
        return numberOfValuesToTake;
    }

    public void accept(MultimapViewVisitable.MultimapViewVisitor visitor) {
        visitor.takeValues(this);
    }
}
