/*
 * Copyright (c) 2008 Kasper Nielsen.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/* 
 * This class was automatically generated by cake.bootstrap.codegen.model.GenerateModel 
 * Available in the https://github.com/cakeframework/cake-developers/ project 
 */
package io.faststream.codegen.model.body;

import java.util.Objects;

import io.faststream.codegen.model.AbstractASTNode;
import io.faststream.codegen.model.body.VariableDeclarator;
import io.faststream.codegen.model.type.Type;
import io.faststream.codegen.model.visitor.CodegenVisitor;
import io.faststream.codegen.model.visitor.ModifyingCodegenVisitor;

/**
 * This class has been autogenerated
 *
 * @author Kasper Nielsen
 */
public class FieldDeclaration extends AbstractASTNode {

    /** The modifiers for the field. */
    private int modifier;

    /** The type of the field. */
    private Type type;

    /** The declarators. */
    private VariableDeclarator declarators;

    public FieldDeclaration() {}

    public FieldDeclaration(int modifier, Type type, VariableDeclarator declarators) {
        this.modifier = modifier;
        this.type = type;
        this.declarators = declarators;
    }

    public int getModifier() {
        return modifier;
    }

    public Type getType() {
        return type;
    }

    public VariableDeclarator getDeclarators() {
        return declarators;
    }

    public void setModifier(int modifier) {
        this.modifier = modifier;
    }

    public void setType(Type type) {
        this.type = type;
    }

    public void setDeclarators(VariableDeclarator declarators) {
        this.declarators = declarators;
    }

    public void accept(CodegenVisitor visitor) {
        visitor.visit(this);
    }

    public Object accept(ModifyingCodegenVisitor visitor) {
        return visitor.visit(this);
    }

    /** {@inheritDoc} */
    public boolean equals(Object other) {
        return other instanceof FieldDeclaration && equals((FieldDeclaration) other);
    }

    public boolean equals(FieldDeclaration other) {
        return super.equals(this) && Objects.equals(modifier, other.modifier) && Objects.equals(type, other.type) && Objects.equals(declarators, other.declarators);
    }

    /** {@inheritDoc} */
    public int hashCode() {
        return Objects.hash(modifier, type, declarators);
    }
}
