/*
 * Copyright (c) 2008 Kasper Nielsen.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/* 
 * This class was automatically generated by cake.bootstrap.codegen.model.GenerateModel 
 * Available in the https://github.com/cakeframework/cake-developers/ project 
 */
package io.faststream.codegen.model.body;

import java.util.Objects;

import io.faststream.codegen.model.AbstractASTNode;
import io.faststream.codegen.model.expression.Expression;
import io.faststream.codegen.model.expression.NameExpression;
import io.faststream.codegen.model.visitor.CodegenVisitor;
import io.faststream.codegen.model.visitor.ModifyingCodegenVisitor;

/**
 * This class has been autogenerated
 *
 * @author Kasper Nielsen
 */
public class VariableDeclarator extends AbstractASTNode {

    /** The name. */
    private NameExpression name;

    /** The number of array dimensions. */
    private int dimensions;

    /** The init expression. */
    private Expression init;

    public VariableDeclarator() {}

    public VariableDeclarator(NameExpression name, int dimensions, Expression init) {
        this.name = name;
        this.dimensions = dimensions;
        this.init = init;
    }

    public NameExpression getName() {
        return name;
    }

    public int getDimensions() {
        return dimensions;
    }

    public Expression getInit() {
        return init;
    }

    public void setName(NameExpression name) {
        this.name = name;
    }

    public void setDimensions(int dimensions) {
        this.dimensions = dimensions;
    }

    public void setInit(Expression init) {
        this.init = init;
    }

    public void accept(CodegenVisitor visitor) {
        visitor.visit(this);
    }

    public Object accept(ModifyingCodegenVisitor visitor) {
        return visitor.visit(this);
    }

    /** {@inheritDoc} */
    public boolean equals(Object other) {
        return other instanceof VariableDeclarator && equals((VariableDeclarator) other);
    }

    public boolean equals(VariableDeclarator other) {
        return super.equals(this) && Objects.equals(name, other.name) && Objects.equals(dimensions, other.dimensions) && Objects.equals(init, other.init);
    }

    /** {@inheritDoc} */
    public int hashCode() {
        return Objects.hash(name, dimensions, init);
    }
}
